[package]
name = "kms"
version = "0.1.0"
authors = ["Tony Arcieri <bascule@gmail.com>"]

[dependencies]
failure = "0.1"
failure_derive = "0.1"
signatory = "0.2.0"
yubihsm = { version = "0.1", optional = true }

[features]
dalek-provider = ["signatory/dalek-provider"]
default = ["dalek-provider"]
yubihsm-provider = ["signatory/yubihsm-provider"]
yubihsm-mockhsm = ["yubihsm-provider", "yubihsm/mockhsm"]

[patch.crates-io]
signatory = { git = "https://github.com/tendermint/signatory" }
