[package]
name = "kms"
version = "0.1.0"
authors = ["Tony Arcieri <tony@iqlusion.io>"]

[dependencies]
failure = "0.1"
failure_derive = "0.1"
serde = "1.0"
serde_derive = "1.0"
signatory = "0.2.0"
structopt = "0.2"
toml = "0.4"
yubihsm = { version = "0.2", optional = true }

[features]
dalek-provider = ["signatory/dalek-provider"]
default = ["dalek-provider", "yubihsm-provider"]
yubihsm-provider = ["signatory/yubihsm-provider"]
yubihsm-mockhsm = ["yubihsm-provider", "yubihsm/mockhsm"]

[patch.crates-io]
signatory = { git = "https://github.com/tendermint/signatory" }
