version: 2

jobs:
  build:
    docker:
      - image: iqlusion/rust-ci:20180602.2 # bump cache keys when modifying this
    environment:
      - CARGO_FEATURES: dalek-provider,yubihsm-mockhsm

    steps:
      - checkout
      - restore_cache:
          key: cache-20180602.2 # bump save_cache key below too
      - run:
          name: rustfmt
          command: |
            cargo +$RUST_NIGHTLY_VERSION fmt --version
            cargo +$RUST_NIGHTLY_VERSION fmt -- --check
      - run:
          name: clippy
          command: |
            cargo +$RUST_NIGHTLY_VERSION clippy --version
            cargo +$RUST_NIGHTLY_VERSION clippy --verbose --features=$CARGO_FEATURES
      - run:
          name: build (nightly, all features)
          command: |
            rustup run $RUST_NIGHTLY_VERSION rustc --version --verbose
            cargo +$RUST_NIGHTLY_VERSION --version --verbose
            cargo +$RUST_NIGHTLY_VERSION build --features=$CARGO_FEATURES
      - run:
          name: test (nightly, all features)
          command: |
            rustup run $RUST_NIGHTLY_VERSION rustc --version --verbose
            cargo +$RUST_NIGHTLY_VERSION --version --verbose
            cargo +$RUST_NIGHTLY_VERSION test --features=$CARGO_FEATURES
      - save_cache:
          key: cache-20180602.2 # bump restore_cache key above too
          paths:
            - "~/.cargo"
            - "./target"
