version: 2

jobs:
  build:
    docker:
    - image: iqlusion/cosmos-kms:20180913.0 # bump cache keys when modifying this
    steps:
    - checkout
    - restore_cache:
        key: cache-20180913.0 # bump save_cache key below too
    - run:
        name: rustfmt
        command: |
          cargo fmt --version
          cargo fmt -- --check
    - run:
        name: clippy
        command: |
          cargo clippy --version
          cargo clippy --all-features
    - run:
        name: build
        command: |
          rustc --version
          cargo --version
          cargo build
    - run:
        name: build --release
        command: |
          rustc --version
          cargo --version
          cargo build --release
    - run:
        name: build --all-features (debug)
        command: |
          rustc --version
          cargo --version
          cargo build --all-features
    - run:
        name: test --all-features
        command: |
          rustc --version
          cargo --version
          cargo test --all-features
    - run:
        name: audit
        command: |
          cargo audit --version
          cargo audit
    - save_cache:
        key: cache-20180913.0 # bump restore_cache key above too
        paths:
        - "~/.cargo"
        - "./target"
